### ISSUE TITLE
Add accessible names to the pdom

### ISSUE THREAD

**Issue by Luisav1** [phetsims/color-vision#153]
@amanda-phet suggested it might be good to add accessible names to CV and @marlitas confirmed that sims are now generally doing that so we'll be adding these before QA testing.

**Comment by Luisav1** [comment]
@terracoda I've added accessible names in the commits above to the Color Vision sim. Could you please review these changes and let me know any thoughts or suggestions you may have? Thanks!

**Comment by Luisav1** [comment]
@amanda-phet volunteered to review these accessible names since @terracoda will be going on vacation soon. Thanks @amanda-phet!

**Comment by amanda-phet** [comment]
I took a quick peek and I like how there are headings for the different controls, that seems nice. I'm a little confused, but Taliesin might have a good idea about this: 

1. There is nothing in the Play Area. I know this is a simple sim, but I'm curious pedagogically if these things are all actually the play area, and only the pause/step and reset all buttons should be in the control area? 
2. Will the Flashlight button read out something about it being on/off? 
3. Will the Filter button say something about it being a toggle switch? I assume that is the case, but wanted to be sure. In the PDOM these things just look like buttons and I don't always know how they will be read out.

**Comment by terracoda** [comment]
Oh, interesting, I think perhaps the old-style process for adding Alternative Input was done before any descriptions were added. 

**Regarding Amanda's questions:**
1. I agree with Amanda, most of the objects need to be in the Play Area. Only the Time Controls and the Reset All button should go in the Control Area.
2. The Flashlight is implemented as a toggle button which only announces it's state on focus - not on a change. On focus, a screen reader reads out "toggle button," when not pressed and "toggle button, selected" when pressed.
3. The Filter button is implemented as an On/Off switch which does automatically announce "on" and "off" when toggled in addition to providing these states on focus: "Filter, on, switch" and "Filter, off, switch."

Even though they look different, I think it makes sense to implement them both as on/off switches. Unfortunately, the switch design pattern may not be working on iOS VoiceOver, due to an apple accessibility bug. For now it might be best to implement them both as regular toggle buttons - THIS NEEDS VERIFICATION by QA on the latest iOS.

**About the Descriptions**...where did they come from? They look different than the ones in the [Interactive Description Design Document](https://docs.google.com/document/d/1hiWQv_GKzyXhjg9D5SyMfOkgdWpZv0NCtIDzNubEtfU/edit) located in the Sim folder.

I think it is great that descriptions were created. I am not suggesting we change them to match the initial ideas in the design document. I recommend 1 update though. Unless there is a good reason not to, I would change: 
- "Flashlight Bulb Color" to just "Bulb Color" as it appears on the screen.  

Or change this in the future when more context is added through help text. Your decision.

**Comment by terracoda** [comment]
I reviewed and unassigned myself. The critical thing to do is the organizational change to move all controls except the Timing Controls and the Reset All button into the Play Area while preserving the same Tab order.

**Comment by Luisav1** [comment]
In the commit above I implemented those changes. All controls except the Timer Controls and the Reset All button are now in the Play Area in the same Tab order and 'Flashlight Bulb Color' is now 'Bulb Color'.

**Comment by terracoda** [comment]
The Play Area and Control Area look good to me. Nice work Luisa!

**Comment by amanda-phet** [comment]
I lost my comment here from an impromptu design meeting yesterday. I asked the Physics folks to weigh in on some of the names, and here are the changes that we would like to see: 

Colored Light --> Monochromatic Light

Photon --> Photons

Brain view options --> Viewer representation
* Hide Brain --> Exterior view
* Show Brain --> Interior view

**Comment by terracoda** [comment]
And just as an aside, I tried screen 1 and 2 with VoiceOver and the Accessible Names and other description provide a lot of very useful context that support understanding of the sonifications. For example, I can play with the bulb color and the filter color. The sonification tells me when no light is getting through and comparing the values on the bulb color and filter color sliders tell me why.

**Comment by terracoda** [comment]
@Luisav1, are you sure you got all the name changes? I still see Hide Brain and Show Brain, but maybe mine is an old version on master.

![Screenshot 2024-07-12 at 14 34 38](https://github.com/user-attachments/assets/1283ffda-52c9-4708-bb82-63b969383f8c)

**Comment by Luisav1** [comment]
Ah yes, I think it might be an old version on master as this is what I see [here](https://bayes.colorado.edu/dev/phettest/color-vision/color-vision_a11y_view.html?brand=phet&ea&debugger):
![image](https://github.com/user-attachments/assets/2cf23fa5-dc10-4ca7-aa1a-070aecbcbd13)

**Comment by amanda-phet** [comment]
Looks good to me! Thanks @Luisav1 !

**Comment by Luisav1** [comment]
Awesome! I just added the strings to the a11y strings so now I believe this is ready.

**Comment by Luisav1** [comment]
I missed two strings, ‘Bulb color’ and ‘Filter color’. I wasn’t sure about duplicating them in the a11y section, but @jbphet confirmed in our standup meeting that it might be a good idea to repeat them since they are only two, just in case the a11y strings are separated out in the future. I have added them in the commit above. This issue is now ready to be closed. Thanks, everyone!

**Comment by Luisav1** [comment]
Removed the duplicate a11y strings in the commit above since in dev meeting today the consensus was that it's fine to use non-translatable strings.
